### ISSUE TITLE
sure bug fixed

### ISSUE THREAD

**Issue by timofurrer** [rogueleaderr/xdist_sure#1]
I just wanted to let you know that I've fixed https://github.com/gabrielfalcao/sure/issues/127 with https://github.com/gabrielfalcao/sure/pull/129 . Thus, you may want to remove this repository.

Thanks for the contribution and cheers :beers:

**Comment by rogueleaderr** [comment]
Big thanks! That will make my life a lot easier at work. I will delete this repository.
